import type { Metadata } from 'next'
import './globals.css'
import { AntdRegistry } from '@ant-design/nextjs-registry'
import StoreProvider from '@/lib/providers/StoreProvider'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`antialiased`}>
				<StoreProvider>
					<AntdRegistry>{children}</AntdRegistry>
				</StoreProvider>
			</body>
		</html>
	)
}
